### ISSUE TITLE
Did not work with babel 6.

### ISSUE THREAD

**Issue by dangreen** [sane/sails-hook-babel#10]
Did not work with babel 6.

**Comment by austinmao** [comment]
Unfortunately, Babel 6 made breaking changes so you should just install babel

```
/** Create .babelrc in root folder to set babel options */
{
  "ignore": [
    "node_modules",
    "bower_components"
  ],
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [
    "transform-react-constant-elements",
    "syntax-async-functions",
    "transform-regenerator"
  ]
}
```

Add to package.json:

```
/** package.json */
{
    "babel-core": "^6.0.17",
    "babel-loader": "^6.0.1",
    "babel-plugin-syntax-async-functions": "^6.0.14",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.0.15",
    "babel-plugin-transform-react-constant-elements": "^6.0.14",
    "babel-plugin-transform-regenerator": "^6.0.17",
    "babel-preset-es2015": "^6.0.15",
}
```

And test with:

```
/** npm test script in package.json */
mocha --compilers js:babel-core/register
```

If you are using ES6/7 like I am, you will need to add to `bootstrap.test.js`:

```
/**
init babel with polyfill for regenerator
@see https://github.com/babel/babel/issues/303
*/
global.babel = require("babel-polyfill")
```

**Comment by mikermcneil** [comment]
For the record, @codymorrison has a good pull request in place here: https://github.com/artificialio/sails-hook-babel/pull/11

Perhaps @Globegitter would be ok with adding @codymorrison or one of you fellas as a contrib so you could help maintain this module?  Thanks everybody for posting.

**Comment by dangreen** [comment]
@mikermcneil I'm doing project on sails using this module, i think i can help with contributing.

**Comment by Globegitter** [comment]
Hey @johnnybridges could you maybe give @codymorrison and @dangreen commit rights to this project, or otherwise move it over to the https://github.com/sane organisation so it can be maintained by the community? Much appreciated.

**Comment by johnnybridges** [comment]
@Globegitter transferred

**Comment by johnnybridges** [comment]
👍

**Comment by Globegitter** [comment]
@johnnybridges thank you!

**Comment by Globegitter** [comment]
@dangreen just gave you write access and merged the babel 6 PR. We can also talk about npm publish rights, just drop me an email.

**Comment by dangreen** [comment]
@Globegitter ok! danon0404@gmail.com

**Comment by mikermcneil** [comment]
@dangreen @johnnybridges @Globegitter :+1: :zap: :zap:   Thanks!  You guys are amazing.

**Comment by dangreen** [comment]
@Globegitter @mikermcneil  I think i will do some commits next week 😉

**Comment by dangreen** [comment]
I think I can close this issue.
