### ISSUE TITLE
Exports seems broken with 0.11.5 and 0.12

### ISSUE THREAD

**Issue by commandline** [sane/sails-hook-babel#13]
See https://github.com/balderdashy/sails/issues/3576

I have tracked down the errors when I try to lift my existing app with either 0.11.5 or 0.12.0 to some changing in how the export keyword handling, in particular, is interacting with the controller registration.

Has anyone else run into oddness with controller actions not being found because of exporting a default object instead of each function out of a controller module?

I can work around that but in doing so, am seeing something else odd that I hope someone else has seen and fixed, that my controller modules are getting clobbered with what looks like some policy configuration.

**Comment by dangreen** [comment]
@commandline [Misunderstanding ES6 Modules, Upgrading Babel, Tears, and a Solution](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.3othbg68x) ?

**Comment by dangreen** [comment]
@commandline http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by commandline** [comment]
Thanks @dangreen, it appears to be more than this and a change from a rc and the final 6.0.1 package. It isn't *just* the change in Babel to follow the es2015 spec more correctly, it is some interaction with that and Sails' hooks to load controllers, policies, etc.

**Comment by commandline** [comment]
This is not a bug with the hook, thanks @dangreen. I was able to get my app working using the hook by adjusting my exports to either export named constants where I could or when Sails expects a top level function from a module, change back to AMD/CommonJS style module.exports instead.

**Comment by dangreen** [comment]
@commandline you can install [babel-plugin-add-module-exports module](https://www.npmjs.com/package/babel-plugin-add-module-exports) and use `export default`

**Comment by commandline** [comment]
I use that plugin for my client bundle, until today, didn't need it for the server code. I just added it to the config for the hook, that did the trick. Thanks.
