### ISSUE TITLE
All routes hanging

### ISSUE THREAD

**Issue by mattcodez** [sane/sails-hook-babel#14]
In upgrading from 5.x to 6.x, I've come across and have solved most of the usual Babel issues. Now that I'm not getting anymore errors though, I'm still unable to use my app. Any page/route I try to go to hangs. That is, the request is sent but a response is never received. `--silly` confirms my routes are being binded properly so not really sure what to make of this.

This is the classic symptom of `res.send(...)` or `res.view(...)` not being called. Haven't messed with any application logic in the port though so I'm kind of stumped as to what to look at next. Only global-ish change I made was adding the Babel plugin "transform-strict-mode". 

It appears my policies are working though as a restricted page will return a 302 redirect to `/login`. But `/login` and other public routes just hang.

Any ideas? Thanks.

**Comment by dangreen** [comment]
@mattcodez these problems can't be because of `sails-hook-babel`

**Comment by mattcodez** [comment]
I know it doesn't make any sense, but it's the only thing I've changed.
There are some subtle changes in syntax support between 5 and 6 (like
exports which have been mentioned in another issue). I'm guessing it's
something like that.

**Comment by mattcodez** [comment]
Yea this turned out to be the export changes again. I was using the broken `export default` syntax for one of my policies. Switched back to CommonJS pattern.
