### ISSUE TITLE
source-map-support breaks sails lift

### ISSUE THREAD

**Issue by hoetmaaiers** [sane/sails-hook-babel#18]
My application uses sails with sails-hook-babel. Sadly `sails lift` breaks with the following errors:

```bash
application/node_modules/sails-hook-babel/node_modules/source-map-support/source-map-support.js:411
      var hasStack = (arguments[1] && arguments[1].stack);
                                                  ^

TypeError: Cannot read property 'filename' of undefined
```

Anyone else having this issue / solution?

**Comment by dangreen** [comment]
@hoetmaaiers can you provide more info? How I can reproduce this?

**Comment by hoetmaaiers** [comment]
Not sure how to reproduce this. When running the same application on other devices, no error is thrown. My solution is running de app in a Docker container.
