### ISSUE TITLE
Upgrade Babel to version 7

### ISSUE THREAD

**Issue by pahan35** [sane/sails-hook-babel#21]
Hi, guys!

What do you think about moving to babel 7?

I've implemented it in my own fork, cause I faced with [an error during overriding async class methods](https://github.com/babel/babel/issues/3930) and to avoid it I update babel.

Do you need those changes as PR to your repo?

**Comment by onoshkodaniil** [comment]
@pahan35 Hi. 

Yes, welcome!

**Comment by dangreen** [comment]
@pahan35 Hi.

Yes, welcome!

**Comment by dangreen** [comment]
@pahan35 https://github.com/sane/sails-hook-babel/releases/tag/v7.0.0
