### ISSUE TITLE
can not debug any more...

### ISSUE THREAD

**Issue by ablipan** [sane/sails-hook-babel#9]
After installed the sails-hook-babel, can not debug any more

**Comment by austinmao** [comment]
See https://github.com/artificialio/sails-hook-babel/issues/10

**Comment by ZelimDamian** [comment]
I am able to debug, but the breakpoint line numbers mismatch as in missing source-maps. So, is there a way to generate source-maps and use them during debugging/

**Comment by dangreen** [comment]
@ablipan @ZelimDamian https://github.com/evanw/node-source-map-support did you try it ?

**Comment by ZelimDamian** [comment]
@dangreen Thanks, I will have a look.
In the meantime for those interested there is an easy (albeit less nice) fix:
Assuming you can provide all babel properties as in https://github.com/artificialio/sails-hook-babel/pull/6 put this
``` javascript 
module.exports.babel = {
  retainLines: true
};
```
in config/babel.js
This will make sure that ES6/JSX/whatever lines match with transpiled code. The result (thus less nice) will look quite bad, but we never see the code anyways.

**Comment by dangreen** [comment]
@ZelimDamian @ablipan https://github.com/sane/sails-hook-babel/commit/f45c1987e2aa5f244d8f77e5eb4acd8454379dbc
